# Generated by Django 4.1.1 on 2022-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestresults',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
