# Generated by Django 4.0.6 on 2022-09-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comunity_alter_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunity',
            old_name='name',
            new_name='full_name',
        ),
    ]
