# Generated by Django 4.0.6 on 2022-09-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_work_flow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work_flow',
        ),
    ]
