# Generated by Django 4.0.6 on 2022-09-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_detail_portfolio_portfolio_portfolio_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='p_name',
        ),
    ]
