# Generated by Django 4.0.6 on 2022-09-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_name_portfolio_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='p_name',
            new_name='portfoli_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
