# Generated by Django 4.0.6 on 2022-09-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_p_name_portfolio_portfoli_type_portfolio_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='port',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfoli_type',
        ),
    ]
