# Generated by Django 4.0.6 on 2022-09-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_port_portfolio_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='portfolio_name',
        ),
    ]
