# Generated by Django 4.0.6 on 2022-09-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_detail_portfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits_portfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='main.portfolio'),
        ),
    ]
