# Generated by Django 4.0.6 on 2022-09-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_benefits_portfolio_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_portfolio',
            name='banefit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
