# Generated by Django 4.0.6 on 2022-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_benefits_portfolio_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_portfolio',
            old_name='banefit_en',
            new_name='banefit_name',
        ),
        migrations.RenameField(
            model_name='detail_portfolio',
            old_name='banefit_uz',
            new_name='banefit_name_en',
        ),
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit',
        ),
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit_ru',
        ),
        migrations.AddField(
            model_name='detail_portfolio',
            name='banefit_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail_portfolio',
            name='banefit_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
