# Generated by Django 4.0.6 on 2022-09-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_banefit_en_detail_portfolio_banefit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit_name',
        ),
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit_name_en',
        ),
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit_name_ru',
        ),
        migrations.RemoveField(
            model_name='detail_portfolio',
            name='banefit_name_uz',
        ),
    ]
